(*
    SPDX-FileCopyrightText: 2025 Jacques Supcik <jacques.supcik@hefr.ch>
    SPDX-License-Identifier: Apache-2.0 OR MIT
*)

syntax = {production}. (* end comment *)
production = identifier "=" expression "." .
expression = (* middle comment *) term {"|" term}.
term = factor {factor}.
(*start (* nested * comment *) comment *) factor = (**)identifier(*(**)*) | string | "(" expression ")" | "[" expression "]" | "{" expression "}". (* end comment *)